// <auto-generated />
using IceCreamVendor.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IceCreamVendor.Core.Migrations
{
    [DbContext(typeof(IceCreamContext))]
    [Migration("20221206172018_IceCreamAdded")]
    partial class IceCreamAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IceCreamVendor.Entities.Entities.IceCream", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Flavour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("IceCream", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Flavour = "vanilla",
                            Price = 1.50m
                        },
                        new
                        {
                            Id = 2,
                            Flavour = "chocolate",
                            Price = 1.50m
                        },
                        new
                        {
                            Id = 3,
                            Flavour = "stracciatella",
                            Price = 1.75m
                        },
                        new
                        {
                            Id = 4,
                            Flavour = "coffee",
                            Price = 1.25m
                        },
                        new
                        {
                            Id = 5,
                            Flavour = "pistachio",
                            Price = 1.80m
                        },
                        new
                        {
                            Id = 6,
                            Flavour = "banana",
                            Price = 1.25m
                        },
                        new
                        {
                            Id = 7,
                            Flavour = "lemon",
                            Price = 1.25m
                        },
                        new
                        {
                            Id = 8,
                            Flavour = "coconut",
                            Price = 1.99m
                        },
                        new
                        {
                            Id = 9,
                            Flavour = "strawberry",
                            Price = 1.99m
                        });
                });

            modelBuilder.Entity("IceCreamVendor.Entities.Entities.Sell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IceCream")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Sell", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientName = "Philémon",
                            IceCream = "vanilla",
                            Price = 1.50m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
